language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: igTwO8CabHQYYfXlGDsNqOyHgvDL5oSx5SkUJ9hs2LGPNvXp7XKj4y1YBPsiIA1W6E1NBgP8TC60MguMi29i9xH1N4DT6UMsRO9e3bZ37IKXbfmoy3HOt/BhKtVL+b6d4kS4S9e7N1yFfA3Q3JAdihYkodHfGeubopuYkh/BsunRdAaqGFnC3suQaHgjFTls+WM6/QQLCGT6uWEucpAABTm5mb2kyEewEfYZcNNJZHSjlzB4RPzJyrIBJXkackCHl1p5W3duYynUpgIzns00H686IWqNu9X88TEfwkaP9pu2opyqyWAuzQLQK5Zc62lKCWsH/wvaipnxTclSVQJerynwc+87XGC1/Hj4+ArDlkEPCvYMK/IlVE5mIhN8bWyA39KIsfPQ64o/0Ymh39UuZ4tab6ao8g6dx+a7z6P1BC3dAr9wC4lWnJaIx/G1YiaNCXsE/qzR11ez943Qw/D+kKApi/gftN5uHgagirIKcDCLLAtwNjvqmX8yEdUdDwGbyuSgupLFWInTB8UOPnR75RJD+OrLmiU2f00NYlTZTDyVwBptfYtrvw4UKGPb6uVJ6dgCe8Rr7Pvr52qBjB4a2zNybX8eAzNe1r84YRCqMUWEaEh2NdACKhyASGOj4GV1+o1htRmTTJ3EANwM0W5j1029IVFYYi06MVo7xaLelTA=
